name: electron-python-retinaface
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - retina-face
      - opencv-python
      - pillow
      - numpy
      - flask
      - flask-cors
      - flask-graphql
      - flask-socketio
      - graphene