site_name: TinyExplorer FaceDetectionApp
site_description: Desktop face detection app for developmental research using YOLO and RetinaFace. Batch processing, CSV outputs, and cross‑platform builds.
site_url: https://andreifoldes.github.io/tinyexplorer-facedetectionapp/
repo_url: https://github.com/andreifoldes/tinyexplorer-facedetectionapp
repo_name: andreifoldes/tinyexplorer-facedetectionapp

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/images/dragon.png
  favicon: assets/images/dragon.png
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Main Features: main-features.md
  - Understanding Results: understanding-results.md
  - Advanced Options: advanced-options.md
  - Troubleshooting: troubleshooting.md
  - Support and Updates: support.md
  - About: about.md

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - meta
